const TYPES = {
  Scene: Symbol.for('Scene'),
  Canvas: Symbol.for('Canvas'),
  ResolverLocator: Symbol.for('ResolverLocator'),
  CoreSettings: Symbol.for('CoreSettings'),
  MVSceneOptimizerService: Symbol.for('MVSceneOptimizerService'),
  CoreWraperElement: Symbol.for('CoreWraperElement'),

  PlatformService: Symbol.for('PlatformService'),
  ActionItemService: Symbol.for('ActionItemService'),
  ActionsService: Symbol.for('ActionsService'),
  AnimationService: Symbol.for('AnimationService'),
  AssetLoaderService: Symbol.for('AssetLoaderService'),
  CameraService: Symbol.for('CameraService'),
  ConfigurationService: Symbol.for('ConfigurationService'),
  EntityService: Symbol.for('EntityService'),
  EventDispatcherService: Symbol.for('EventDispatcherService'),
  JsonService: Symbol.for('JsonService'),
  LightService: Symbol.for('LightService'),
  MaterialService: Symbol.for('MaterialService'),
  MeshService: Symbol.for('MeshService'),
  SceneSettingsService: Symbol.for('SceneSettingsService'),
  TextureService: Symbol.for('TextureService'),
  ActionItemController: Symbol.for('ActionItemController'),
  AnimationController: Symbol.for('AnimationController'),
  CameraController: Symbol.for('CameraController'),
  ControlsController: Symbol.for('ControlsController'),
  EnvironmentController: Symbol.for('EnvironmentController'),
  LightController: Symbol.for('LightController'),
  ProductController: Symbol.for('ProductController'),
  SceneController: Symbol.for('SceneController'),
};

export { TYPES };
