pipeline {
    agent {
        docker {
          image 'node:10.21.0'
          label 'docker-large'
          args '--network=host'
        }
    }
    stages {
        stage('setup') {
            steps {
                sh 'curl -sL https://aka.ms/InstallAzureCLIDeb | bash'
                sh 'az --version'
                sh 'npm i'
            }
        }
        stage('build') {
            steps {
                sh """
                    npm run build
                """
            }
        }
        stage("deploy") {
            environment {
                AZURE_STORAGE_ACCOUNT_KEY = credentials('mv-webgl-core-azure-storage-account-key')
            }
            steps {
                sh """
                    TAG_NAME=\$(git tag --sort version:refname | tail -1)
                    echo \$TAG_NAME
                    az storage blob upload-batch -d mountedtowebapp/\$TAG_NAME -s dist --account-name mvwebglcore --account-key $AZURE_STORAGE_ACCOUNT_KEY
                """
            }
        }
    }
}
